import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { celo, celoAlfajores } from "wagmi/chains";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { http, WagmiProvider, createConfig } from "wagmi";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const connectors = connectorsForWallets(
//   [
//       {
//           groupName: "Recommended",
//           wallets: [injectedWallet],
//       },
//   ],
//   {
//       appName: "Celo Composer",
//       projectId: "044601f65212332475a09bc14ceb3c34",
//   }
// );

const config = createConfig({
  // connectors,
  chains: [celo, celoAlfajores],
  transports: {
      [celo.id]: http(),
      [celoAlfajores.id]: http(),
  },
});

const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <WagmiProvider config={config}>
      <body className={inter.className}>{children}</body>
      </WagmiProvider>
    </html>
  );
}
